pre-commit-config 구성
f-lab-edu/anomaly-factory pull request #1
Opened 2024-01-14 13:48 UTC by tyjeon24

수정사항은 아래와 같습니다.
* pyproject.toml
    * pre-commit 패키지를 추가하였습니다.
* .pre-commit-config.yaml
    * pre-commit-hooks : 파일의 불필요한 공백(trailing-whitespace)이나 들여쓰기 등을 수정합니다.
    * isort : import를 정렬합니다.
    * black : 코드 포매터입니다. line length를 120으로 설정하였습니다.
    * flake8 : pep8을 포함한 코딩 컨벤션을 따르는지 검사합니다.
    * autoflake : 미사용 import 및 변수를 없앱니다.
    * pydocstyle : docstring이 올바르게 작성되었는지 검사합니다.

2024-01-14 13:52 UTC, tyjeon24 commented
멘토님, 이슈 #2 에 대해 참조를 등록하려면 커밋 메시지에 작성해야 하는지, 아니면 pull request에 명시해야 하는지 질문드립니다. 감사합니다.

2024-01-15 02:16 UTC, f-lab-zion commented on .pre-commit-config.yaml
isort, black, flake8, autoflake 까지 pre commit 구성은 잘해주셨네요

2024-01-15 02:35 UTC, f-lab-zion requested changes
👍 몇가지 보완 요청드립니다

2024-01-15 02:35 UTC, f-lab-zion commented on pyproject.toml
> +readme = "README.md"
이번 PR에 `README.md` 파일도 작성해서 추가해주세요. README 작성은 스타일이 다르겠지만 기본적으로 포함되야할 점은 다음과 같습니다.
- 프로젝트 제목
- 프로젝트에 대한 간략한 설명 (max 10줄 이하로 간략하게 작성을 추천)
- 프로젝트 아키텍처  (사용하는 DB 등 외부 컴포넌트 , 외부 API 연동 등)
- Requirements ( 파이썬 버전, 주요 라이브러리 등) 
- 설치 및 실행 방법

2024-01-15 02:35 UTC, f-lab-zion commented on pyproject.toml
> +readme = "README.md"
`.gitignore` 도 추가해주세요

2024-01-15 02:37 UTC, f-lab-zion commented
> 수정사항은 아래와 같습니다.
> 
> * pyproject.toml
>   
>   * pre-commit 패키지를 추가하였습니다.
> * .pre-commit-config.yaml
>   
>   * pre-commit-hooks : 파일의 불필요한 공백(trailing-whitespace)이나 들여쓰기 등을 수정합니다.
>   * isort : import를 정렬합니다.
>   * black : 코드 포매터입니다. line length를 120으로 설정하였습니다.
>   * flake8 : pep8을 포함한 코딩 컨벤션을 따르는지 검사합니다.
>   * autoflake : 미사용 import 및 변수를 없앱니다.
>   * pydocstyle : docstring이 올바르게 작성되었는지 검사합니다.

여기 밑에 closes #1 을 추가하시면 자동으로 Issue와 연결됩니다 참고하세요

2024-01-21 15:35 UTC, tyjeon24 commented on pyproject.toml
> +readme = "README.md"
변경 사항입니다.

1. README.md 항목을 변경하였습니다.
2. .gitignore에 Python 및 VSCode에 대한 ignore 항목을 추가하였습니다.

2024-01-23 04:37 UTC, f-lab-zion approved these changes
👍 LGTM 코멘트 하나만 확인하시고 머지해주세요

2024-01-23 04:37 UTC, f-lab-zion commented on pyproject.toml
> +pre-commit = "^3.6.0"
pre-commit, black, flake8 등은 dev-dependency 로 포함하면 차후 구분하기 좋습니다.

2024-01-24 10:53 UTC, merged