Feature/2/skleran fastapi
f-lab-edu/anomaly-factory pull request #4
Opened 2024-01-29 14:25 UTC by tyjeon24

# 요약
* sklearn과 fastapi를 활용한 모델 서빙 코드입니다. 서빙 가능한 최소의 코드를 목표로 작성했습니다.

# 변경사항
* 모델 학습, 배포
  * train.py : 서빙에 필요한 모델을 학습하였습니다.
  * iris_classification_model.joblib : 학습된 모델입니다.
  * main.py : 모델 서빙을 위한 fastAPI 코드입니다.
* 패키지
  * poetry.lock : 의존성(scikit-learn, fastapi)이 추가되었습니다.
  * pyproject.toml : 의존성(scikit-learn, fastapi)이 추가되었습니다.
* README
  * README.md : 프로젝트 목표 및 일정을 구체화하였습니다.
  * assets/using_mlops_tools.png : README.md에 사용된 이미지입니다.

2024-01-30 03:56 UTC, f-lab-zion requested changes
👍 리뷰 코멘트 검토 부탁드립니다

2024-01-30 03:56 UTC, f-lab-zion commented on main.py
> +model = load('iris_classification_model.joblib')
model 이 늘어날 수 있으니 `model` 폴더를 만들어서 따로 관리하는게 어떨까요

2024-01-30 03:56 UTC, f-lab-zion commented on main.py
> +    param4: float
Feature name으로 바꿔야 의미를 알 수 있습니다. 참고해서 변경해보면 어떨까요 
```python
iris.feature_names
>>>
['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']
```

2024-01-30 03:56 UTC, f-lab-zion commented on main.py
> +    return get_prediction(params.param1, params.param2, params.param3, params.param4)
get_prediction 의 파라미터로 param을 하나씩 입력받는 것보다  `IrisModel ` 클래스를 활용하는 방향으로 변경해보세요
pydantic model을 왜 써야하는지 다시 한번 생각해보시고 코멘트로 남겨주세요.

2024-02-04 14:53 UTC, tyjeon24 commented on main.py
> +    param4: float
![image](https://github.com/f-lab-edu/anomaly-factory/assets/47409372/82d69327-e295-42a8-90f9-b936e923b98d)

수정하였습니다.

2024-02-04 15:03 UTC, tyjeon24 commented on main.py
> +    return get_prediction(params.param1, params.param2, params.param3, params.param4)
![image](https://github.com/f-lab-edu/anomaly-factory/assets/47409372/4040a519-0252-41e2-bc96-f1547c33fc12)

pydantic은 데이터 검증을 통해 데이터가 타입과 제약사항을 지키도록 보장하기 위해 사용합니다.
model은 타입과 제약사항 검사를 위해  pydantic에서 일반적으로 권장하기 때문에 사용됩니다. model 클래스는 데이터 검증을 수행하며, 이외에도 직렬화 등 부가적인 기능을 제공합니다.

2024-02-06 10:39 UTC, f-lab-zion requested changes
Pydantic model을 보다 적극적으로 활용하는 방식을 제안드립니다. 이렇게 했을때 어떤 기대효과가 있을지 한번 생각해보시고 코멘트 남겨주세요.

2024-02-06 10:39 UTC, f-lab-zion commented on main.py
> +def get_prediction(sepal_length, sepal_width, petal_length, petal_width) -> dict:
```suggestion
def get_prediction(iris_model: IrisModel) -> dict:
```

2024-02-06 10:39 UTC, f-lab-zion commented on main.py
> +    return get_prediction(data.sepal_length, data.sepal_width, data.petal_length, data.petal_width)
```suggestion
    return get_prediction(data)
```

2024-02-06 10:39 UTC, f-lab-zion commented on main.py
> +    x = [[sepal_length, sepal_width, petal_length, petal_width]]
```suggestion
    x = [list(iris.dict().values())]
```

2024-03-04 12:04 UTC, tyjeon24 commented on main.py
> +def get_prediction(sepal_length, sepal_width, petal_length, petal_width) -> dict:
해당 제안사항 적용하여 변경하였습니다. Pydantic 모델 활용 시 다음을 기대할 수 있습니다.
1. 데이터의 입력 형식을 검증할 수 있습니다.
2. 데이터의 입력 순서를 검증할 수 있습니다(X1이 들어갈 자리에 X2를 입력하는 경우 순서를 바로잡을 수 있습니다).
3. 코드가 간결해집니다. 간결한 코드는 유지 보수에 유리합니다.

2024-03-04 12:04 UTC, tyjeon24 commented on main.py
> +    return get_prediction(data.sepal_length, data.sepal_width, data.petal_length, data.petal_width)
적용하였습니다.

2024-03-04 12:04 UTC, tyjeon24 commented on main.py
> +    x = [[sepal_length, sepal_width, petal_length, petal_width]]
적용하였습니다.

2024-03-04 12:04 UTC, tyjeon24 commented on main.py
> +    x = [[sepal_length, sepal_width, petal_length, petal_width]]
멘토님, Resolve conversation은 언제 누르면 되는지 질문드립니다.

2024-03-07 12:40 UTC, f-lab-zion commented on config.py
> +path = {"sklearn_model": Path(MODEL_DIRECTORY, "iris_classification_model.joblib")}
pydantic 의 BaseSetting 을 활용한 방안은 어떨까요? [link](https://docs.pydantic.dev/latest/concepts/pydantic_settings/)

2024-03-11 15:55 UTC, tyjeon24 commented on config.py
> +path = {"sklearn_model": Path(MODEL_DIRECTORY, "iris_classification_model.joblib")}
너무 좋은 의견 감사합니다. config을 다른 사람이 쓰도록 작성할 때 안내 문구를 작성하는 경우가 보통입니다.
예를 들어,
```python
api_key = "YOUR_API_KEY"
```
이런 식으로 적는 것보다,
```python
api_key = "DwsacvzpqwIF353+4=="
```
이런 식으로 적는 편이 더 직관적이나 이게 예시인지 기본값인지 또 명시해주어야 하는 문제가 있습니다.

pydantic은 변수에 대한 validator를 제공하고 있어서(PostgresDsn, RedisDsn 등) 이런 부분을 해결하기 용이할 것 같습니다. 감사합니다!

2024-03-11 15:55 UTC, merged