Feature/3/mlflow xgboost
f-lab-edu/anomaly-factory pull request #7
Opened 2024-01-30 13:59 UTC by tyjeon24

# 요약
* mlflow 및 xgboost를 기반으로 한 experiment tracking 기능을 추가하였습니다.
* 사용자가 튜닝된 데이터를 바로 활용할 수 있도록 구현하였습니다.

# 변경사항
* xgboost_tuner.py
  * 입력된 데이터에 대해 하이퍼파라미터 튜닝을 수행하고, metric을 기록하며 최적의 모델에 대한 artifact를 저장합니다.
  ```python
  # poetry shell 환경에서 mlflow ui를 입력해 Tracking UI를 먼저 실행해야 합니다.
  from sklearn.datasets import load_breast_cancer
  X, y = load_breast_cancer(as_frame=True, return_X_y=True)
  tuner = XgboostTuner()
  tuner.tune_model(X, y)
  ```

* 패키지
  * poetry.lock : mlflow, optuna, xgboost를 추가하였습니다.
  * pyproject.toml : mlflow, optuna, xgboost를 추가하였습니다.

* pre-commit
  * .pre-commit-config.yaml : line-length 값을 120으로 수정하였습니다.

# 비고
## xgboost 선정 이유
* **LinearRegression, RandomForest 등 sklearn 기반 모델이 아닌 이유**
  * 베이스라인 모델로서의 xgboost는 파라미터 튜닝 없이도 충분한 성능을 보장하기 때문입니다.
  * 공정에서는 단순 선형 회귀 모델보다 복잡한 수식 모델을 사용합니다.
  * AI의 도입 목적은 예측 성능을 높이는 데 주된 목적이 있으므로, 수식 모델보다는 더 나은 metric을 갖는 모델을 사용해야 하기 때문에 앙상블 모델을 선정했고, 프로젝트에 자주 사용되는 xgboost 모델을 채택했습니다.

* **lightgbm이 아닌 이유**
    * 별도의 의존성을 요구하지 않으면서 충분히 좋은 성능을 보장하기 때문입니다.
    * 회사의 Edge PC는 Air gap 환경이면서 타부서 자산이기 때문에 docker를 비롯한 프로그램 설치가 제한됩니다.
    * [lightgbm](https://github.com/microsoft/LightGBM/tree/master/python-package)은 리눅스 환경에서 설치 시 glibc 등을 요구하나, 위 사유로 해당 패키지를 설치하기 어렵습니다.

2024-01-31 05:34 UTC, f-lab-zion requested changes
👍 코멘트 추가했습니다.
XgboostTuner 클래스에 대한 unit test 코드가 빠져있습니다. 이 부분 추가도 부탁드립니다.

2024-01-31 05:34 UTC, f-lab-zion commented on xgboost_tuner.py
> +            experiment_name (str, optional): Experiment 이름입니다. 기본값은 "XGBoostExperiment"입니다.
optional 이 맞을까요? mandatory가 되야하진 않을까요?

2024-01-31 05:34 UTC, f-lab-zion commented on xgboost_tuner.py
> +        mlflow.xgboost.load_model(model_uri)
return value에 대한 처리는 따로 없는데 어떤 용도의 코드인가요?

2024-01-31 05:34 UTC, f-lab-zion commented on xgboost_tuner.py
> +    ):
return value가 없는데 결과가 잘 되었는지 확인은 어디서 할 수 있나요?

2024-01-31 05:34 UTC, f-lab-zion commented on xgboost_tuner.py
> +            model_uri = mlflow.get_artifact_uri(artifact_path)
with 구문 내에서 Exception이 발생하면 어떤 일이 발생할까요?

2024-01-31 05:34 UTC, f-lab-zion commented on xgboost_tuner.py
> +            error = root_mean_squared_error(self.valid_y, model.predict(self.valid_x))
이 함수의 return 값은 error 변수입니다. error 변수에 RMSE 함수의 결과를 저장하기 앞서 오류가 발생하면 어떻게 처리해야 할까요?

2024-03-04 13:05 UTC, tyjeon24 commented on xgboost_tuner.py
> +            experiment_name (str, optional): Experiment 이름입니다. 기본값은 "XGBoostExperiment"입니다.
수정했습니다.

2024-03-04 13:07 UTC, tyjeon24 commented on xgboost_tuner.py
> +        tracking_uri: str = "http://localhost:5000",
config.py 파일 추가하였습니다.

2024-03-04 15:10 UTC, tyjeon24 commented on xgboost_tuner.py
> +        mlflow.xgboost.load_model(model_uri)
해당 리뷰 의견을 기반으로 아래 이슈를 생성하였습니다.
#8 
사용자가 mlflow 서버를 거치지 않고 모델의 결과를 볼 수 있도록 기능을 구현하였습니다.

2024-03-04 15:20 UTC, tyjeon24 commented on xgboost_tuner.py
> +            error = root_mean_squared_error(self.valid_y, model.predict(self.valid_x))
아래 형태와 같이 발생할 수 있는 에러를 고려하고, raise된 오류를 처리하는 코드를 작성하면 안정적으로 작동합니다.

이런 상황을 대응하기 위해 테스트 코드를 작성이 필요해보이나 어떤 코드로 정상 작동을 보장할 수 있을지는 고민해보아야 할 것 같습니다.

https://github.com/optuna/optuna/issues/2163#issuecomment-752818449

```python
import optuna


def objective(trial: optuna.trial.Trial) -> float:

    x = trial.suggest_float("x", 0, 1)
    if x < 0.5:
        raise RuntimeWarning
    return x


def main():
    study = optuna.create_study()
    study.optimize(objective, n_trials=10, catch=(RuntimeWarning,))


if __name__ == '__main__':
    main()
```

2024-03-07 13:14 UTC, f-lab-zion approved these changes
👍 하나만 확인하시고 머지하셔도 좋습니다

2024-03-11 16:15 UTC, tyjeon24 commented on config.py
> +}
확인하였습니다. 해당 개선안은 #12 이슈에서 구현합니다.

2024-03-12 12:08 UTC, merged

2024-03-12 12:09 UTC, tyjeon24 commented
#5 이슈는 해당 머지로 구현하였습니다.